### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by merwok** [caravancoop/configstore#23]
We have unit tests for each class but not for the whole system.

envvar: run in sub-processes?

dotenv: test missing file, unreadable file, empty file, invalid file

docker secret: run with fake filesystem? run in container?

aws ssm: use moto to connect to a fake SSM API

**Comment by just1602** [comment]
Qu'est-ce que tu veux dire par run in sub-processes? Je me code un petit script qui call configstore et je le run avec subprocess genre ?

**Comment by merwok** [comment]
Oui, histoire de vraiment tester le fonctionnement des envvars.

**Comment by merwok** [comment]
@JulienLabonte is going to write an integration tests that combines envvars and a dotenv file.
